-- Cấu hình file vật lý
CREATE DATABASE QLSINHVIEN1
ON 
( 
    NAME = QLSINHVIEN1_Data,
    FILENAME = 'C:\SQL_Data\QLSINHVIEN1_Data.mdf',
    SIZE = 100MB,
    MAXSIZE = 500MB,
    FILEGROWTH = 10MB
)
LOG ON
( 
    NAME = QLSINHVIEN1_Log,
    FILENAME = 'C:\SQL_Data\QLSINHVIEN1_Log.ldf',
    SIZE = 30MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5MB
);
GO

USE QLSINHVIEN1;
GO

-- Bảng KHOA 
CREATE TABLE KHOA (
    Ma_Khoa VARCHAR(10) PRIMARY KEY,
    Ten_Khoa NVARCHAR(100),
    Nam_TL INT,
    Phong_Khoa VARCHAR(20),
    CONSTRAINT UK_KHOA_TenKhoa UNIQUE (Ten_Khoa)
);
GO

-- Bảng BOMON
CREATE TABLE BOMON (
    Ma_BM VARCHAR(10) PRIMARY KEY,
    Ten_BM NVARCHAR(100),
    Phong_BM VARCHAR(20),
    Email_BM VARCHAR(50),
    Ma_Khoa VARCHAR(10) NOT NULL,
    CONSTRAINT UK_BOMON_Email UNIQUE (Email_BM),
    CONSTRAINT UK_BOMON_TenBM_Khoa UNIQUE (Ten_BM, Ma_Khoa),
    CONSTRAINT FK_BM_Khoa FOREIGN KEY (Ma_Khoa) REFERENCES KHOA(Ma_Khoa)
);
GO

-- Bảng LOPHANHCHINH
CREATE TABLE LOPHANHCHINH (
    Ma_Lop VARCHAR(10) PRIMARY KEY,
    Ten_Lop NVARCHAR(50),
    Si_So INT,
    Nien_Khoa VARCHAR(20),
    Ma_Khoa VARCHAR(10) NOT NULL,
    CONSTRAINT UK_LOPHANHCHINH_TenLop UNIQUE (Ten_Lop),
    CONSTRAINT FK_LHC_Khoa FOREIGN KEY (Ma_Khoa) REFERENCES KHOA(Ma_Khoa)
);
GO

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    Ma_SV VARCHAR(10) PRIMARY KEY,
    HoDemSV NVARCHAR(50),
    Ngay_Sinh_SV DATE,
    SDT_SV VARCHAR(15),
    Email_SV VARCHAR(50),
    TT_Hoctap NVARCHAR(20),
    Ten_SV NVARCHAR(30),
    Dia_Chi NVARCHAR(100),
    Ma_Lop VARCHAR(10) NOT NULL,
    Gioi_tinh_SV NVARCHAR(5),
    CONSTRAINT UK_SINHVIEN_Email UNIQUE (Email_SV),
    CONSTRAINT UK_SINHVIEN_SDT UNIQUE (SDT_SV),
    CONSTRAINT FK_SV_LHC FOREIGN KEY (Ma_Lop) REFERENCES LOPHANHCHINH(Ma_Lop)
);
GO

-- Bảng MONHOC
CREATE TABLE MONHOC (
    Ma_MH VARCHAR(10) PRIMARY KEY,
    Ten_MH NVARCHAR(100),
    So_Tiet_LT INT,
    So_Tiet_TH INT,
    So_Tin_Chi INT,
    Ma_BM VARCHAR(10) NOT NULL,
    CONSTRAINT UK_MONHOC_TenMH UNIQUE (Ten_MH),
    CONSTRAINT FK_MH_BM FOREIGN KEY (Ma_BM) REFERENCES BOMON(Ma_BM)
);
GO

-- Bảng HOCKY
CREATE TABLE HOCKY (
    Ma_HK VARCHAR(10) PRIMARY KEY,
    Ten_HK NVARCHAR(50) NOT NULL,
    Nam_Hoc VARCHAR(20) NOT NULL,
    Ky_Trong_Nam INT NOT NULL,
    Ngay_Bat_Dau DATE,
    Ngay_Ket_Thuc DATE,
    CONSTRAINT UK_HOCKY_NamHoc_Ky UNIQUE (Nam_Hoc, Ky_Trong_Nam)
);
GO

-- Bảng GIANGVIEN
CREATE TABLE GIANGVIEN (
    Ma_GV VARCHAR(10) PRIMARY KEY,
    Ten_GV NVARCHAR(50) NOT NULL,
    SDT_GV VARCHAR(15),
    Ngay_Sinh_GV DATE,
    Gioi_Tinh_GV NVARCHAR(5),
    Email_GV VARCHAR(50),
    Hoc_Vi NVARCHAR(20),
    Ma_BM VARCHAR(10) NOT NULL,
    CONSTRAINT UK_GIANGVIEN_Email UNIQUE (Email_GV),
    CONSTRAINT UK_GIANGVIEN_SDT UNIQUE (SDT_GV),
    CONSTRAINT FK_GV_BM FOREIGN KEY (Ma_BM) REFERENCES BOMON(Ma_BM)
);
GO

-- Bảng LOPHOCPHAN
CREATE TABLE LOPHOCPHAN (
    Ma_LHP VARCHAR(10) PRIMARY KEY,
    SL_Toi_Da INT,
    Phong_Hoc VARCHAR(20),
    Lich_Hoc NVARCHAR(100),
    Ma_MH VARCHAR(10) NOT NULL,
    Ma_HK VARCHAR(10) NOT NULL,
    Ma_GV VARCHAR(10) NOT NULL,
    CONSTRAINT FK_LHP_MH FOREIGN KEY (Ma_MH) REFERENCES MONHOC(Ma_MH),
    CONSTRAINT FK_LHP_HK FOREIGN KEY (Ma_HK) REFERENCES HOCKY(Ma_HK),
    CONSTRAINT FK_LHP_GV FOREIGN KEY (Ma_GV) REFERENCES GIANGVIEN(Ma_GV)
);
GO

-- Bảng DIEM
CREATE TABLE DIEM (
    Ma_SV VARCHAR(10) NOT NULL,
    Ma_LHP VARCHAR(10) NOT NULL,
    Diem_CC DECIMAL(3,1),
    Diem_GK DECIMAL(3,1),
    Diem_CK DECIMAL(3,1),
    CONSTRAINT PK_Diem PRIMARY KEY (Ma_SV, Ma_LHP),
    CONSTRAINT FK_Diem_SV FOREIGN KEY (Ma_SV) REFERENCES SINHVIEN(Ma_SV),
    CONSTRAINT FK_Diem_LHP FOREIGN KEY (Ma_LHP) REFERENCES LOPHOCPHAN(Ma_LHP),
    CONSTRAINT CHK_Diem_CC CHECK (Diem_CC >= 0 AND Diem_CC <= 10),
    CONSTRAINT CHK_Diem_GK CHECK (Diem_GK >= 0 AND Diem_GK <= 10),
    CONSTRAINT CHK_Diem_CK CHECK (Diem_CK >= 0 AND Diem_CK <= 10)
);
GO

-- Bảng DANGKY
CREATE TABLE DANGKY (
    Ma_SV VARCHAR(10) NOT NULL,
    Ma_LHP VARCHAR(10) NOT NULL,
    CONSTRAINT PK_DangKy PRIMARY KEY (Ma_SV, Ma_LHP),
    CONSTRAINT FK_DK_SV FOREIGN KEY (Ma_SV) REFERENCES SINHVIEN(Ma_SV),
    CONSTRAINT FK_DK_LHP FOREIGN KEY (Ma_LHP) REFERENCES LOPHOCPHAN(Ma_LHP)
);
GO
